
CREATE TABLE itineraries (
   id     INT AUTO_INCREMENT PRIMARY KEY,
   name   varchar(255),
   state  mediumtext ,
   time   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
